apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore
spec:
  provider:
    gcpsm:
      projectID: abount-me
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: dev-gcpsm-secret-001
            key: secret-access-credentials

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  refreshInterval: 10s

  secretStoreRef:
    kind: SecretStore
    name: dev-secretstore-001

  target:
    name: dev-secret
    creationPolicy: Owner

  data:
    - secretKey: DEBUG
      remoteRef:
        key: dev_about_me-DJANGO_DEBUG
        version: latest

    - secretKey: DJANGO_SETTINGS_MODULE
      remoteRef:
        key: dev_about_me-DJANGO_SETTINGS_MODULE
        version: latest

    - secretKey: DJANGO_SECRET_KEY
      remoteRef:
        key: dev_about_me-DJANGO_SECRET_KEY
        version: latest

    - secretKey: DATABASE_URL
      remoteRef:
        key: dev_about_me-DATABASE_URL
        version: latest

    - secretKey: DJANGO_ALLOWED_HOSTS
      remoteRef:
        key: dev_about_me-DJANGO_ALLOWED_HOSTS
        version: latest
