name: Update image

on:
  repository_dispatch:
    types:
      - update-image

env:
  PROJECT_ID: abount-me
  REGION: asia-northeast1
  BASE_REPOGITORY_ID: about-me-api-repository
  BASE_DOCKER_IMAGE_NAME: abount-me-api

jobs:
  update-yml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Env
        run: |
          echo GITHUB_REF"=${{ github.event.client_payload.ref }}" >> $GITHUB_ENV
          echo GITHUB_SHA"=${{ github.event.client_payload.github_sha }}" >> $GITHUB_ENV

      - name: Update deployment.yml for dev
        if: ${{ env.GITHUB_REF }} == 'develop'
        uses: mikefarah/yq@master
        with:
          cmd: IMAGE_TAG=' ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/dev-${{ env.BASE_REPOGITORY_ID }}/dev-${{ env.BASE_DOCKER_IMAGE_NAME }}:${{ env.GITHUB_SHA }}' yq e '.[2].value = env(IMAGE_TAG)' -i overlays/dev/deployment.yml

      - name: Update deployment.yml for prd
        if: ${{ env.GITHUB_REF }} == 'main'
        uses: mikefarah/yq@master
        with:
          cmd: IMAGE_TAG=' ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/prd-${{ env.BASE_REPOGITORY_ID }}/prd-${{ env.BASE_DOCKER_IMAGE_NAME }}:${{ env.GITHUB_SHA }}' yq e '.[2].value |= env(IMAGE_TAG)' -i overlays/prd/deployment.yml

      - name: Open merge request
        id: omr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: create-pull-request/release/${{ env.GITHUB_SHA }}
          base: ${{ env.GITHUB_REF }}
          delete-branch: true
          title: |
            [${{ env.GITHUB_SHA }}] Update Container Image
          body: |
            [${{ env.GITHUB_SHA }}] Update Container Image
            - Updated container image
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            update container image
            ${{ env.GITHUB_SHA }} release
          assignees: butterthon
          draft: false
